version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: leadhelper
      MARIADB_USER: leaduser
      MARIADB_PASSWORD: leadpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
