spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    show-summary: summary

  application:
    name: LeadHelper

  datasource:
    url: jdbc:mariadb://localhost:3306/leadhelper
    username: leaduser
    password: leadpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none  # Disable Hibernate's schema management
    properties:
      hibernate:
        format_sql: true
        show_sql: true
